src/Entity/Event/Event.php
<?php

namespace App\Entity\Event;

use App\Entity\User;
use App\Repository\Event\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event extends BaseEvent
{
    #[ORM\OneToMany(mappedBy: 'event', targetEntity: EventSubscription::class, orphanRemoval: true)]
    /** @var Collection<EventSubscription> $eventSubscriptions */
    private Collection $eventSubscriptions;

    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'events')]
    private Collection $tags;

    #[ORM\ManyToOne(inversedBy: 'events')]
    private ?RecurringEvent $recurringEvent = null;

    #[ORM\OneToMany(mappedBy: 'event', targetEntity: Question::class, orphanRemoval: true)]
    /** @var ?Collection<Question> $questions */
    public ?Collection $questions = null;

    public function __construct()
    {
        parent::__construct();
        $this->eventSubscriptions = new ArrayCollection();
        $this->tags = new ArrayCollection();
        $this->questions = new ArrayCollection();
    }

    public function isNotPastSubscriptionDeadline(?\DateTime $date = null): bool
    {
        if ($this->getSubscriptionDeadline() === null) {
            return true;
        }
        if ($date === null) {
            $date = new \DateTime();
        }
        return $this->getSubscriptionDeadline() > $date;
    }

    public function isNotPastStartDate(?\DateTime $date = null): bool
    {
        if ($this->getStartDate() === null) {
            return true;
        }
        if ($date === null) {
            $date = new \DateTime();
        }
        return $this->getStartDate() > $date;
    }

    /**
     * @return Collection<int, EventSubscription>
     */
    public function getEventSubscriptions(): Collection
    {
        return $this->eventSubscriptions;
    }

    public function addEventSubscription(EventSubscription $eventSubscription): static
    {
        if (!$this->eventSubscriptions->contains($eventSubscription)) {
            $this->eventSubscriptions->add($eventSubscription);
            $eventSubscription->setEvent($this);
        }

        return $this;
    }

    public function removeEventSubscription(EventSubscription $eventSubscription): static
    {
        if ($this->eventSubscriptions->removeElement($eventSubscription)) {
            // set the owning side to null (unless already changed)
            if ($eventSubscription->getEvent() === $this) {
                $eventSubscription->setEvent(null);
            }
        }

        return $this;
    }

    public function getAmountOfSubscriptions(): int
    {
        $amount = 0;
        foreach ($this->eventSubscriptions as $eventSubscription) {
            $amount += $eventSubscription->getAmount();
        }
        return $amount;
    }

    public function isSubscribed(User $user): bool
    {
        return $this->getSubscription($user) !== null;
    }

    public function getSubscription(?User $user): ?EventSubscription
    {
        if ($user === null) {
            return null;
        }
        foreach ($this->eventSubscriptions as $eventSubscription) {
            if ($eventSubscription->getCreatedUser() === $user) {
                return $eventSubscription;
            }
        }
        return null;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): static
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }

        return $this;
    }

    public function removeTag(Tag $tag): static
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function setTags(Collection $tags): static
    {
        $this->tags = $tags;

        return $this;
    }

    public function getRecurringEvent(): ?RecurringEvent
    {
        return $this->recurringEvent;
    }

    public function setRecurringEvent(?RecurringEvent $recurringEvent): static
    {
        $this->recurringEvent = $recurringEvent;

        return $this;
    }
}

src/Controller/Event/CalendarController.php
<?php

namespace App\Controller\Event;

use App\Entity\Event\Event;
use App\Entity\Event\Tag;
use App\Entity\User;
use App\Repository\Event\EventRepository;
use App\Repository\Event\TagRepository;
use App\Transformer\EventCalTransformer;
use DateInterval;
use DateTimeImmutable;
use Eluceo\iCal\Domain\Entity\Calendar;
use Eluceo\iCal\Domain\Entity\TimeZone;
use Eluceo\iCal\Domain\Enum\TimeZoneTransitionType;
use Eluceo\iCal\Domain\ValueObject\TimeZoneTransition;
use Eluceo\iCal\Presentation\Factory\CalendarFactory;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/event/calendar', name: 'event_calendar')]
class CalendarController extends AbstractController
{
    public function __construct(
        private readonly EventRepository     $eventRepository,
        private readonly EventCalTransformer $eventCalTransformer,
    ) {}

    #[Route('/index', name: '_index')]
    public function index(TagRepository $tagRepository): Response
    {
        return $this->render('event/calendar/index.html.twig', [
            'tags' => $tagRepository->findAll(),
        ]);
    }

    #[Route('/all/cal.ics', name: '_all')]
    public function cal(): Response
    {
        return $this->getCalendarResponse($this->eventRepository->findAll(), 'all');
    }

    #[Route('/user/{user}/cal.ics', name: '_user')]
    public function user(User $user): Response
    {
        return $this->getCalendarResponse($this->eventRepository->findSubscribedByUser($user), 'user');
    }

    #[Route('/tag/{tag}/cal.ics', name: '_tag')]
    public function tag(Tag $tag): Response
    {
        return $this->getCalendarResponse($this->eventRepository->findByTag($tag), 'tag_' . $tag);
    }

    /**
     * @param array<Event> $events
     * @return Response
     */
    private function getCalendarResponse(array $events, string $name): Response
    {
        $calendar = new Calendar();
        $now = new DateTimeImmutable();
        $timeZone = TimeZone::createFromPhpDateTimeZone(
            new \DateTimeZone('Europe/Amsterdam'),
            $now->sub(new DateInterval('P1Y')),
            $now->add(new DateInterval('P3Y'))
        );
        $calendar->addTimeZone($timeZone);
        foreach ($events as $event) {
            $calendar->addEvent($this->eventCalTransformer->transform($event));
        }
        $calendar
            ->setProductIdentifier('buitensport_durf_events_' . $name)
            ->setPublishedTTL(new DateInterval('PT1H'))
        ;

        $componentFactory = new CalendarFactory();
        $calendarComponent = $componentFactory->createCalendar($calendar);

        return new Response($calendarComponent, 200, [
            'Content-Type' => 'text/calendar; charset=utf-8',
            'Content-Disposition' => 'attachment; filename="cal.ics"',
        ]);
    }

    /**
     * @return TimeZone
     */
    public function getTimeZone(): TimeZone
    {
        return (new TimeZone('Europe/Amsterdam'))
            ->addTransition(new TimeZoneTransition(
                TimeZoneTransitionType::STANDARD(),
                new DateTimeImmutable('2024-10-27T03:00:00'),
                0,
                3600,
                'CET'
            ))->addTransition(new TimeZoneTransition(
                TimeZoneTransitionType::DAYLIGHT(),
                new DateTimeImmutable('2023-03-31T02:00:00'),
                3600,
                0,
                'CEST'
            ))
        ;
    }
}

src/Controller/Event/EventController.php
<?php

namespace App\Controller\Event;

use App\Entity\Event\Event;
use App\Entity\User;
use App\Form\ConfirmationType;
use App\Form\Event\EventType;
use App\Repository\Event\EventRepository;
use App\Repository\Event\TagRepository;
use DateInterval;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/event/event', name: 'event_event')]
class EventController extends AbstractController
{
    #[Route('/index', name: '_index')]
    public function index(
        Request         $request,
        EventRepository $eventRepository,
        TagRepository   $tagRepository
    ): Response
    {
        $tagName = $request->query->get('tag');
        $tag = $tagRepository->findOneBy(['name' => $tagName]);

        return $this->render('event/event/index.html.twig', [
            'events' => $eventRepository->findByTag($tag, $tagRepository->findIsDefaultHide()),
            'tags' => $tagRepository->findAll(),
            'tag' => $tag,
        ]);
    }

    #[Route('/past', name: '_past')]
    public function past(EventRepository $eventRepository): Response
    {
        return $this->render('event/event/past.html.twig', [
            'events' => $eventRepository->findPast(),
        ]);
    }

    #[Route('/new', name: '_new')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $event = new Event();
        $event->setDuration(new DateInterval('PT0S'));
        $form = $this->createForm(EventType::class, $event);
        $form->add('Save', SubmitType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('event_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/event/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/show', name: '_show')]
    public function show(Event $event): Response
    {
        return $this->render('event/event/show.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/{id}/edit', name: '_edit')]
    public function edit(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->add('Save', SubmitType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('event_event_show', ['id' => $event->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/event/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: '_delete')]
    public function delete(Request $request, Event $event, EventRepository $repository): Response
    {
        $form = $this->createForm(ConfirmationType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $repository->remove($event);

            $this->addFlash('success', sprintf('Deleted event "%s"', $event));
            return $this->redirectToRoute('event_event_index');
        }

        return $this->render('general/confirmation.form.html.twig', [
            'message' => sprintf('Are you sure you want to delete event "%s"?', $event),
            'form' => $form->createView(),
        ]);
    }
}

src/Controller/Event/EventSubscriptionController.php
<?php

namespace App\Controller\Event;

use App\Entity\Event\Event;
use App\Entity\Event\EventSubscription;
use App\Entity\Event\QuestionAnswer;
use App\Entity\User;
use App\Form\Event\EventSubscriptionType;
use App\Form\Event\QuestionAnswerType;
use App\Repository\Event\EventSubscriptionRepository;
use App\Repository\Event\QuestionAnswerRepository;
use App\Security\Voter\EventSubscriptionVoter;
use App\Security\Voter\EventVoter;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/event/subscription', name: 'event_subscription')]
class EventSubscriptionController extends AbstractController
{
    public function __construct(
        private readonly EventSubscriptionRepository $repository,
    ) {}

    #[Route('/subscribe/{id}', name: '_subscribe')]
    public function subscribe(
        Request                  $request,
        Event                    $event,
        QuestionAnswerRepository $answerRepository,
    ): Response
    {
        /** @var User $user */
        $user = $this->getUser();

        // Redirect if already subscribed
        if ($user && $event->isSubscribed($user) && !$this->isGranted('ROLE_EVENT_ADMIN')) {
            return $this->redirectToRoute('event_subscription_edit', [
                'id' => $event->getSubscription($user)->getId(),
            ]);
        }

        // Check permissions
        if (!$this->isGranted(EventVoter::SUBSCRIBE, $event)) {
            if ($user) {
                $this->addFlash('error', 'You cannot subscribe to this event');
                return $this->redirectToRoute('event_event_show', [
                    'id' => $event->getId(),
                ]);
            } else {
                return $this->redirectToRoute('event_subscription_nologin', [
                    'id' => $event->getId(),
                ]);
            }
        }

        $subscription = new EventSubscription();
        $subscription
            ->setCreatedDateNowNoSeconds()
            ->setEvent($event)
            ->setAmount(1)
            ->setCreatedUser($user)
        ;

        foreach ($event->questions as $question) {
            $answer = new QuestionAnswer();
            $answer->question = $question;
            $answer->subscription = $subscription;
        }

        $form = $this->createForm(EventSubscriptionType::class, $subscription);

        if ($this->isGranted('ROLE_EVENT_ADMIN')) {
            $form->add('createdUser', options: [
                'query_builder' => fn($er) => $er->createQueryBuilder('u')->orderBy('u.name', 'ASC'),
                'label' => 'To subscribe user',
            ]);
        }
        $form->add('subscribe', SubmitType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (!$this->isGranted('ROLE_EVENT_ADMIN') && $user !== $subscription->getCreatedUser()) {
                $this->addFlash('error', 'You can only subscribe to your own events');
                return $this->redirectToRoute('event_event_show', ['id' => $event->getId()]);
            }

            $this->repository->save($subscription);
            $this->addFlash('success', sprintf('You have subscribed to %s', $event));
            return $this->redirectToRoute('event_event_show', ['id' => $event->getId()]);
        }

        return $this->render('event/subscription/subscribe.html.twig', [
            'form' => $form->createView(),
            'event' => $event,
        ]);
    }

    #[Route('/unsubscribe/{id}', name: '_unsubscribe')]
    public function unsubscribe(EventSubscription $subscription): Response
    {
        $this->denyAccessUnlessGranted(EventVoter::UNSUBSCRIBE, $subscription->getEvent());

        $event = $subscription->getEvent();
        $this->repository->delete($subscription);
        $this->addFlash('success', sprintf('You have unsubscribed from %s', $event));
        return $this->redirectToRoute('event_event_show', ['id' => $event->getId()]);
    }

    #[Route('/{id}/edit', name: '_edit')]
    public function edit(EventSubscription $subscription, Request $request): Response
    {
        $this->denyAccessUnlessGranted(EventSubscriptionVoter::EDIT, $subscription);

        // Add missing question answers
        foreach ($subscription->getEvent()->questions as $question) {
            $found = false;
            foreach ($subscription->questionAnswers as $answer) {
                if ($answer->question === $question) {
                    $found = true;
                    break;
                }
            }
            if (!$found) {
                $answer = new QuestionAnswer();
                $answer->question = $question;
                $answer->subscription = $subscription;
            }
        }

        $form = $this->createForm(EventSubscriptionType::class, $subscription)
            ->add('save', SubmitType::class)
        ;

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->repository->save($subscription);
            $this->addFlash('success', sprintf('Updated subscription to %s', $subscription->getEvent()));
            return $this->redirectToRoute('event_event_show', ['id' => $subscription->getEvent()->getId()]);
        }

        return $this->render('event/subscription/edit.html.twig', [
            'subscription' => $subscription,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/nologin/{id}', name: '_nologin')]
    public function notLoggedIn(Event $event): Response
    {
        return $this->render('event/subscription/not_logged_in.html.twig', [
            'event' => $event,
        ]);
    }
}

templates/event/event/card.html.twig
{# @var event App\Entity\Event\Event #}
{% set subscription = event.subscription(app.user) %}
<div class="card">
    {% if event.image %}
        <img class="card-img-top" src="{{ vich_uploader_asset(event.image) }}" alt="{{ event.name }} image">
    {% endif %}

    <div class="card-body">
        <h5 class="card-title">{{ event }}</h5>
        <p class="card-text"><small class="text-muted">
                {% for tag in event.tags %}
                    <span class="badge bg-primary">{{ tag }}</span>
                {% endfor %}<br>
                Start: {{ event.startDate ? event.startDate|fdate_time : '' }} <br>
                End: {{ event.startDate ? (event.startDate.add(event.duration))|fdate_time : '' }} <br>
                Duration: {{ event.duration|time_duration }} <br>
                Location: {{ event.location }}
                {% if event.amountOfSubscriptions > 0 %}
                    <br>Subscriptions: <span class="badge bg-success rounded-pill">{{ event.amountOfSubscriptions }}</span>
                {% endif %}
            </small></p>
        <p class="card-text">{{ event.description|truncate(100)|markdown_to_html }}</p>
    </div>

    <ul class="list-group list-group-flush">
        {% if subscription %}
            <li class="list-group-item list-group-item-success d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">You are subscribed</div>
                <span class="badge bg-success rounded-pill">{{ subscription.amount }}</span>
            </li>
        {% endif %}
    </ul>

    <div class="card-body">
        <div class="btn-group">
            {% if is_granted('subscribe', event) or not is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                <a class="btn btn-success"
                   href="{{ path('event_subscription_subscribe', {'id': event.id}) }}">Subscribe</a>
            {% endif %}
            {% if subscription and is_granted('unsubscribe', event) %}
                <a class="btn btn-info"
                   href="{{ path('event_subscription_unsubscribe', {'id': subscription.id}) }}">Unsubscribe</a>
            {% endif %}
        </div>
        <div class="btn-group">
            <a class="btn btn-info" href="{{ path('event_event_show', {'id': event.id}) }}">Details</a>
            {% if is_granted('ROLE_EVENT_EDIT') %}
                <a class="btn btn-warning" href="{{ path('event_event_edit', {'id': event.id}) }}">Edit</a>
            {% endif %}
        </div>
    </div>
</div>

templates/event/event/edit.html.twig
{% extends 'base/single.column.html.twig' %}

{% set title %}Edit Event {{ event }}{% endset %}

{% block body %}
    <a class="btn btn-primary" href="{{ path('event_event_index') }}">Back to list</a>
    <a class="btn btn-danger" href="{{ path('event_event_delete', {'id': event.id}) }}">Delete</a>

    {{ form(form) }}
{% endblock %}

templates/event/event/index.html.twig
{% extends 'base/single.column.html.twig' %}

{% set title %}Upcoming events{% endset %}

{% block body %}
    <p>
        Welcome to the event page of BuitenSport Durf. Here you can find all the upcoming events.
        If you want to add the events to your own calendar, click on the calendars button.
        To see the past events, click on the button below.
    </p>
    <a class="btn btn-primary" href="{{ path('event_calendar_index') }}">Calendars</a>
    <a class="btn btn-secondary" href="{{ path('event_event_past') }}">Past events</a>
    {% if is_granted('ROLE_EVENT_EDIT') %}
        <a class="btn btn-success" href="{{ path('event_event_new') }}">Create new</a>
    {% endif %}
    {% if is_granted('ROLE_EVENT_RECURRING') %}
        <a class="btn btn-warning" href="{{ path('event_recurring_event_index') }}">Recurring events</a>
    {% endif %}

    <h5>Tags</h5>
    <p>
        Below you can find all the tags that are used for events.
        Click on a tag to filter the events by that tag.
        The red tags are hidden by default.
    </p>
    {% for tagOption in tags %}
        {% if tagOption == tag %}
            <a class="btn btn-success" href="{{ path('event_event_index') }}">{{ tagOption }}</a>
        {% else %}
            <a class="btn btn-{% if tagOption.defaultHide %}danger{% else %}primary{% endif %}"
               href="{{ path('event_event_index', {tag: tagOption.name}) }}">{{ tagOption }}</a>
        {% endif %}
    {% endfor %}
    <br><br>

    <h5>Events</h5>
    <p>
        Below you can find all the upcoming events.
        Click on an event to see more information about it.
        {% if not app.user %}
            If you want to subscribe to an event, please
            <a href="{{ path('register') }}">register</a>
            or <a href="{{ path('login') }}">login</a>.
        {% endif %}
    </p>
    <div class="row row-cols-1 row-cols-md-3 g-3">
        {% for event in events %}
            <div class="col">
                {{ include('event/event/card.html.twig', {event: event}) }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/event/event/new.html.twig
{% extends 'base/single.column.html.twig' %}

{% set title %}Create Event{% endset %}

{% block body %}
    {{ form(form) }}
{% endblock %}

templates/event/event/past.html.twig
{% extends 'base/single.column.html.twig' %}

{% set title %}Past events{% endset %}

{% block body %}
    <div class="row row-cols-1 row-cols-md-3 g-3">
        {% for event in events %}
            <div class="col">
                {{ include('event/event/card.html.twig', {event: event}) }}
            </div>
        {% endfor %}
    </div>
{% endblock %}